language: node_js
node_js:
- node

install:
- pip install --user awscli
- npm install

script:
- make deploy

branches:
  only:
  - master

env:
  global:
  - secure: 4STgxbNZMOV9rZ2VjEydnljvlaJRIdRJLcNRhXjmBg1MBuDifH13s4eg6sR+aG/gQUIKfn0qQNPJMNp77XkXW1e2Ensze1HtoPKcytFnfq4tiu4Fzo7WOM87q3K5nuUFwuqo1gFHiPJO/qoz/pOSHpr3QvCLPrvN+lGsP4HjETqK5qlx6HoHAyzg2Zjz7CE9YaNeayocioHtulUu7SRgDoJbSM7aQu+7xa8Gcb4o4yCYnC2M0G2dR1a8+fYhmdN8IMNpN3ZvazfJ6ikT66ABvwgCnSkDSK58pZ7u/XA0/4bei9Ph+7IAC37BbNx5djVDiER/y/rb8AksEjQShsK6npplVPN5asxKmGm+69NFn0YxKWomMcWsvpEYjFk0L9huJb6/+0vS1vAKW4DEfHtxG7r7QMMsxuwY/boU3R0kKn3lbQ7MBcgW6ugQbTqvcw7io+4D3KHYGEY3Nk4bGo0vmKw77Tv97TWah9pNMHArx70HV+ZDtdj1jOQhLDAs0wHj689YI2BNi58mjPg/VGTmXfG2X4CYUO/CWJhRjvLFYv7XvJRljuaEwMMsTOuJbh/6VsDA+2ABRfrEMD4zLm3UsLLdcdSYS6pzAGJuHqNBnwslLrWFWPuwaE0xByzkSYaR6dexEi/7eS4b6ZVLkfJ2Y61YrMYeydMz9+01HOzoMsE=
  - secure: 5ZtfP6gamOC0yM5fA6Yt1iYRDmbvG7QQW0s0K/Pv2bmfLnXMtb/1AfggwkpLhpbP/HYlfVbjIIbCBpPAUuh5MEsCGkjwnbyhTR+h9w15HeYwvVuEdqK3bUE7GNr7VemUem7AkSJsOJcb0SFUUXGuSdnCIaZxK8tNaDAosFmgAhLgHdKhIYL6hKASbNmeHXohnz8PFCL6CY6Hi1Opc/IOhGf48VjFy7WCWU6zkxXZ1fngvVr8DbzC5of4DPDlnWeu4eVTy8aePtjf/TGXV+K+DN0lzgiXmWc0crjWbJTEAg7XyYS/CCem94XIPlpsCkJuGkKCbhngvCJA/B/4FT/pZpTRopN4JRuGuEMJBHm/vG9voqNtl1nC/pt94QFZsyLOy/C41vW0O+HsKGhASiSqw6hK+OtQdoq3kZ/qFxitmCOxD1G/MOFovnuipXl0GpAs7X4dRJPRhC+2q71pNGmwBNS8ltQbeI8IiQ8EWByEfen6cbppeW8GrBzxk756RQSeHJLDHr3bC2YqVzcZd2FfCPFCx0IdyLAg9RROPb5eAEzKjDo3s1qpSWHdHS2kPFRqdJwi12onoa9q22wHKdlgp2rp07wOMl0SsrARiei3NPtpjPLoWuEsINAReKrI0l0bwJN4UY8iXmxFCuC4HMaBx8/nneqK4cPYsteJbuCfgQk=
