navMap:
  profile: '&#x43;'
  resume: '&#x3a;'
  book: '&#x59;'
  contact: '&#x21;'

social:
  links:
    - 'https://github.com/akinjide'
    - 'https://www.linkedin.com/in/akinjide'

  icons:
    - '&#x33;'
    - '&#x60;'

  titles:
    - 'Github'
    - 'LinkedIn'

books:
  tags:
    - 'All'
    - 'Programming'
    - 'Design'
    - 'Engineering'
    - 'Architecture'
    - 'DevOps'
    - 'Security'
    - 'Databases'
    - 'UI And UX'

  completed:
    - name: 'Mean Machine'
      url: 'https://leanpub.com/mean-machine'
      tags:
        - 1

    - name: 'Learn Python the Hard Way'
      url: 'https://www.amazon.com/Learn-Python-Hard-Way-Introduction/dp/0321884914'
      tags:
        - 1

    - name: 'Building Scalable Apps with Redis and Nodejs'
      url: 'https://www.packtpub.com/web-development/building-scalable-apps-redis-and-nodejs'
      tags:
        - 1
        - 3

    - name: 'The Heroku Hackers Guide'
      url: 'https://www.theherokuhackersguide.com'
      tags:
        - 4
        - 3

    - name: 'Expressjs Middleware'
      url: 'https://ewiggin.gitbooks.io/expressjs-middleware/content/index.html'
      tags:
        - 1
        - 6

    - name: 'Node Security'
      url: 'https://www.packtpub.com/web-development/node-security'
      tags:
        - 1
        - 6

    - name: 'Swift for Beginners Develop And Design'
      url: 'https://www.goodreads.com/book/show/23818508-swift-for-beginners'
      tags:
        - 1
        - 2

    - name: 'You Dont know JS (Up And Going)'
      url: 'https://www.amazon.com/You-Dont-Know-JS-Going/dp/1491924462'
      tags:
        - 1

    - name: 'You Dont know JS (Scope And Closure)'
      url: 'https://www.amazon.com/You-Dont-Know-JS-Closures/dp/1449335586'
      tags:
        - 1

legal:  >
  This website uses cookies to customize your experience,
  and deliver personalized content,
  i'll assume you're ok with this.
  By using this website, you will be deemed to have agreed.

resume:
  employment:
    - role: 'Programmer'
      company: 'Andela'
      timeline: 'May 2015 - Present'
      description: >
        Andela is a technology company that helps companies build high performing
        distributed engineering teams by investing in Africa’s most talented software
        engineers, with centres in Lagos, Kampala, Nairobi, San Francisco and New York City.
        <br>
        <br>
        At Andela, we believe brilliance is evenly distributed with an acceptance
        rate below 1%. I am exposed to working with partners like Udacity and Atlas Money,
        without technological stack limitations.
        <br>
        More information about my roles at these companies can be found below.

    - role: 'Software Architect'
      company: 'Andela'
      timeline: 'May 2018 - Present'
      description: >
        As an architect, I analyse and design system architecture for software products,
        create technology roadmaps highlighting milestones.

    - role: 'Technical Team Lead'
      company: 'Atlas Money'
      timeline: 'Feb 2018 - Jun 2018'
      description: >
        As a TTL;
        <br>
        <br>
        I shifted fractionally from debugging the software we are building, to
        debugging the team by identifying and clearing roadblocks.
        <br>
        <br>
        Managing technical debt effectively to ensure it does not accumulate.
        <br>
        <br>
        Broaden the technical capabilities of the team by delegating problems of
        increasing complexity, pair programming frequently to promote engineering
        practices and provide technical guidance.

    - role: 'Technical Team Lead'
      company: 'Andela'
      timeline: 'Sept 2017 - May 2018'
      description: >
        As a TTL;
        <br>
        <br>
        Lead Andela's Partner team responsible for building scalable software products
        and tools necessary for operating and scaling the business
        effectively.
        <br>
        <br>
        Drafting and deploying new strategies to effectively build and manage a
        high velocity and performing engineering team.
        <br>
        <br>
        Interfacing and liaising with teammates to ensure the product’s development
        and personal growth, and better team dynamics.

    - role: 'Mentor'
      company: 'Codementor'
      timeline: 'Feb 2017 - Present'
      description: >
        As a Mentor, I spend a lot of time reading other people’s code and
        using my expertise in various technologies to constantly help fix annoying bugs,
        scale tech stacks, or provide just any information that can help.

    - role: 'Writer'
      company: 'Scotch'
      timeline: 'Jan 2017 - Present'
      description: >
        At Scotch, I write posts about various technologies in the world
        of software development and programming.

    - role: 'Consultant'
      company: 'Andela'
      timeline: 'Oct 2016 - Sept 2017'
      description: >
        As a consultant;
        <br>
        <br>
        Collaborate with software architects and engineers to plan, design, develop,
        test, deploy and maintain software applications.
        <br>
        <br>
        Proactively influence software best practices, standards, and policies
        within Andela's Partner team and interfacing with stakeholders including Product Owner;
        Project Managers; Business Analysts, to understand user requirements and extract
        technical requirements.

    - role: 'Backend Engineer'
      company: 'Atlas Money'
      timeline: 'Mar 2016 - Jun 2018'
      description: >
        As a backend engineer, I collaborate with other engineers to build, develop,
        test and maintain scalable Microservices using (but not limited to) Node.js
        and several technologies (e.g. PostgreSQL, MongoDB, ElasticSearch, Vue.js,
        Angular.js, and Apache Kafka) to solve business requirements facing mobile banking.

    - role: 'Frontend Engineer'
      company: 'Udacity'
      timeline: 'Jan 2016 - Mar 2016'
      description: >
        As a frontend engineer, I focused on implementing UI designs using Zeplin, CSS Liquid,
        JavaScript, Angular.js, and jQuery.

    - role: 'Junior Engineer'
      company: 'Andela'
      timeline: 'Dec 2015 - Oct 2016'
      description: >
        As a junior engineer;
        <br>
        <br>
        I constantly gain skills and experience needed to thrive by working
        with a broad range technologies, build cool stuffs in Python, Node.js --
        as well as various web frameworks.
        <br>
        <br>
        I attend meetups, give talks on programming, design and related topics,
        and actively contribute to the open source community.

    - role: 'Editor'
      company: 'FashionPolice'
      timeline: 'Jan 2015 - Mar 2015'
      description: >
        As an Editor, I spent my time primarily writing fashion news,
        articles and learned some cool stuff.

  education:
    - where: 'Self Taught'
      timeline: '2014 - Present'
      level: 'Life'
      description: >
        I'm primarily self-taught. I've been designing since I was roughly 18 years
        old, and have read through hundreds of design books, tutorials and articles.
        Plus I'm continually expanding my knowledge and open to learning.

    - where: 'Lagos City Senior College'
      timeline: '2010 - 2012'
      level: 'High School, Science'
      description: >
        I was a science student, a member of Jet club back at school and
        also graduated from this great school.

  portfolios:
    - title: 'ufus-extension'
      timeline: 'Jul 2018'
      language: 'Node.js, JavaScript, CSS, Chrome, Open source'
      description: >
        Ufus browser extension.
        <br>
        <br>
        <a href="https://github.com/akinjide/ufus-extension" target="_blank">https://github.com/akinjide/ufus-extension</a>

    - title: 'is'
      timeline: 'Feb 2018'
      language: 'Node.js, JavaScript, Open source'
      description: >
        IS a type checking for JavaScript.
        <br>
        <br>
        <a href="https://github.com/akinjide/is" target="_blank">https://github.com/akinjide/is</a>

    - title: 'size'
      timeline: 'Jun 2017'
      language: 'Node.js, JavaScript, Open source'
      description: >
        Black market currency rate instantly in your terminal.
        <br>
        <br>
        <a href="https://github.com/akinjide/size" target="_blank">https://github.com/akinjide/size</a>

    - title: 'aboki-node'
      timeline: 'May 2017'
      language: 'Node.js, JavaScript, Open source'
      description: >
        Black market currency rate instantly in your terminal.
        <br>
        <br>
        <a href="https://github.com/akinjide/aboki-node" target="_blank">https://github.com/akinjide/aboki-node</a>

    - title: 'aboki'
      timeline: 'Apr 2017'
      language: 'Python, Open Source'
      description: >
        Black market currency rate instantly in your terminal.
        <br>
        <br>
        <a href="https://github.com/akinjide/aboki" target="_blank">https://github.com/akinjide/aboki</a>

    - title: 'tw-syntax'
      timeline: 'Feb 2017'
      language: 'TextWrangler, BBEdit, Open source'
      description: >
        BBEdit/TextWrangler Language Module and Syntax highlighting.
        <br>
        <br>
        <a href="https://github.com/akinjide/tw-syntax" target="_blank">https://github.com/akinjide/tw-syntax</a>

    - title: 'aproxy'
      timeline: 'Dec 2016'
      language: 'JavaScript, Node.js, Open source'
      description: >
        Renders PDF using phantom.js and Node.js.
        <br>
        <br>
        <a href="https://github.com/akinjide/aproxy" target="_blank">https://github.com/akinjide/aproxy</a>

    - title: 'cookiet'
      timeline: 'Jun 2016'
      language: 'JavaScript, Open source'
      description: >
        A small, simple JavaScript cookies library.
        <br>
        <br>
        <a href="https://github.com/akinjide/cookiet" target="_blank">https://github.com/akinjide/cookiet</a>

  communityContrib:
    - role: 'Lead'
      timeline: 'May 2016 - Present'
      group: 'Facebook Developer Circle: Lagos'
      description: >
        A forum for developers in Lagos and its surroundings who are interested
        in building on the Facebook platform to interact and collaborate with other developers
        who share similar interests.
        <br>
        <br>
        <a href="https://www.facebook.com/groups/DevCLagos/" target="_blank">https://www.facebook.com/groups/DevCLagos/</a>

  skills:
    programming:
      'Python': 4
      'Node.js': 6
      'GoLang': 2
      'Ruby': 3
      'Swift / iOS': 2
      'Flask': 2
      'Express.js': 6
      'Angular.js': 5
      'Vue.js': 4
      'VIM': 3
      '/(No)?SQL/': 5
      'TDD': 4
      'Git / Github': 5

    design:
      'CSS': 6
      'HTML': 7
      'Pug': 7
      'JavaScript': 5
      'JQuery': 6
      'Photoshop': 3
      'illustrator': 3
      'Sketch 3': 7
      'Style': 4
      'Creativity': 5

    more:
      'Gaming': 6
      'Skating': 2
      'Surfing Youtube': 6
      'Writing': 4
      'Public Speaking': 3
      'German': 2
